goalee/config/routes.rb
Rails.application.routes.draw do
  resources :users, only: [:new, :create, :show]
  resources :goals, only: [:create, :new, :show, :update, :delete]
  resources :user_comments, only: [:create]
  resources :goal_comments, only: [:create]
  resource :session, only: [:new, :create, :destroy]
end

goalee/app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

goalee/app/models/goal.rb
class Goal < ApplicationRecord

  validates :title, :details, :user_id, presence: true
  validates :private, :completed, inclusion: {in: [true, false]}

  belongs_to :user

  has_many :comments,
    foreign_key: :goal_id,
    class_name: :GoalComment

end

goalee/app/models/goal_comment.rb
class GoalComment < ApplicationRecord
  validates :author_id, :body, :goal_id, presence: true

  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User

  belongs_to :goal,
    foreign_key: :goal_id,
    class_name: :Goal
end

goalee/app/models/user.rb
class User < ApplicationRecord
  validates :username, :session_token, :password_digest, presence: true
  validates :password, length: {minimum: 6, allow_nil: true}
  validates :username, :session_token, uniqueness: true

  after_initialize :ensure_session_token

  has_many :goals

  has_many :comments,
    foreign_key: :author_id,
    class_name: :UserComment

  attr_reader :password

  def self.find_by_credentials(username, password)
    user = User.find_by(username: username)
    # debugger
    if user && user.is_password?(password)
      user
    else
      nil
    end
  end

  def reset_session_token!
    self.session_token = User.generate_token
    self.save
    self.session_token
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def self.generate_token
    SecureRandom.urlsafe_base64(16)
  end

  def ensure_session_token
    self.session_token ||= User.generate_token
  end

end

goalee/app/models/user_comment.rb
class UserComment < ApplicationRecord
  validates :author_id, :body, :commentee_id, presence: true

  belongs_to :author,
    foreign_key: :author_id,
    class_name: :User

  belongs_to :commentee,
    foreign_key: :commentee_id,
    class_name: :User
end

goalee/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception

  helper_method :current_user
  helper_method :logged_in?
  
  def current_user
    @current_user ||= User.find_by(session_token: session[:session_token])
  end

  def login(user)
    @current_user = user
    session[:session_token] = user.reset_session_token!
  end

  def logout
    current_user.reset_session_token!
    session[:session_token] = nil
  end

  def logged_in?
    !!current_user
  end

  def require_logged_in
    redirect_to new_session_url unless logged_in?
  end






end

goalee/app/controllers/goal_comments_controller.rb
class GoalCommentsController < ApplicationController

  before_action :require_logged_in


  def create
    @comment = GoalComment.new(comment_params)
    @comment.author_id = current_user.id
    if @comment.save
      redirect_to goal_url(@comment.goal_id)
    else
      flash[:errors] = @comment.errors.full_messages
      redirect_to goal_url(@comment.goal_id)
    end
  end

  private

  def comment_params
    params.require(:goal_comment).permit(:body, :commentee_id)
  end
end

goalee/app/controllers/goals_controller.rb
class GoalsController < ApplicationController

  before_action :require_logged_in


  def create
    @goal = current_user.goals.new(goal_params)
    if @goal.save
      redirect_to goal_url(@goal.id)
    else
      flash.now[:errors] = @goal.errors.full_messages
      render :new
    end
  end

  def new
    @goal = Goal.new
    render :new
  end

  def show
    @goal = Goal.find(params[:id])
    if @goal.private
      redirect_to user_url(@goal.user.id) unless @goal.user.id == current_user.id
    end
  end

  def update

  end

  def delete

  end

  private

  def goal_params
    params.require(:goal).permit(:title, :details, :private, :completed)
  end

end

goalee/app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

def new
end

def create
  user = User.find_by_credentials(params[:user][:username], params[:user][:password])
  if user
    login(user)
    redirect_to user_url(user.id)
  else
    flash.now[:errors] = user.errors.full_messages
    render :new
  end
end

def destroy
  logout
  redirect_to new_session_url
end

end

goalee/app/controllers/user_comments_controller.rb
class UserCommentsController < ApplicationController

    before_action :require_logged_in

    def new

    end

    def create

    end

    def show

    end

    def update

    end

    def delete

    end

end

goalee/app/controllers/users_controller.rb
class UsersController < ApplicationController

  before_action :require_logged_in, only: [:show]

  def new

  end

  def create
    user = User.new(user_params)
    if user.save
      login(user)
      redirect_to user_url(user.id)
    else
      redirect_to new_user_url
    end
  end

  def show

  end

  private

  def user_params

    params.require(:user).permit(:username, :password)
  end

end

goalee/app/helpers/application_helper.rb
module ApplicationHelper
end

goalee/app/helpers/goal_comments_helper.rb
module GoalCommentsHelper
end

goalee/app/helpers/goals_helper.rb
module GoalsHelper
end

goalee/app/helpers/user_comments_helper.rb
module UserCommentsHelper
end

goalee/app/views/goals/new.html.erb
<h1>Create New Goal</h1>


<form class="" action="<%= goals_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">

<label for="">Title
  <input type="text" name="goal[title]" value="">
</label>

<label for="">Details
  <textarea name="goal[details]"></textarea>
</label>

<label for="">Private?
  <input type="checkbox" name="goal[private]">
</label>

<label for="">Completed?
  <input type="checkbox" name="goal[completed]">
</label>

<input type="submit" name="" value="New Goal">
</form>

goalee/app/views/goals/show.html.erb
<h2>Title: <%= @goal.title %> </h2>
<h3>Details: <%= @goal.details %> </h3>
<h3>Visibility: <%= @goal.private ? "Private" : "Public" %> </h3>
<h3>Finished?: <%= @goal.completed ? "Completed" : "Ongoing" %> </h3>

goalee/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Goalee</title>
    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <% if logged_in? %>
      <h3><%= current_user.username %></h3>
      <form class="" action="<%= session_url %>" method="post">
        <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %> ">
        <input type="hidden" name="_method" value="DELETE">
        <button type="submit" name="button">Log Out</button>
      </form>
    <% end %>

    <%= yield %>
  </body>
</html>

goalee/app/views/users/new.html.erb
<h2>New User</h2>
<form class="" action="<%= users_url %>" method="post">
  <input type="hidden" name="authenticity_token" value="<%= form_authenticity_token %>">
  <label for="">Username
    <input type="text" name="user[username]" value="">
  </label>

  <label for="">Password
    <input type="text" name="user[password]" value="">
  </label>

  <input type="submit" name="" value="Create User">
</form>

goalee/app/views/users/show.html.erb
<h1>RABABABA</h1>